const express = require('express');
const fs = require('fs');
const app = express();
const port = 3000;

function htmlStart(res, title){
    res.write(`<!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title> ${title} </title>
    </head>
    <body>`);
};

function htmlEnd(res){
    res.write(`</body>
    </html>`);
    res.end();
};

app.get('/', (req,res) => {
    htmlStart(res, 'hi');
    res.write('<p> hello </p>');
    htmlEnd(res);
})

//using await and async
app.get('/api', async (req,res) => {
    try{
    htmlStart(res);
    res.write(`<h1> this page generated by the server </h1>`);
    res.write(`<a href = "/api.html"> go to static page </a>`);

    // let fRes = await fetch(`http://phish.in/api/v1/songs/ ${req.query.snum}.json`);

    let fRes = await fetch(`http://localhost:3001/${req.query.state}/${req.query.age}`);
    let data = await fRes.json();
    
        for (let death of data.results){
            res.write(`<h1> ${death.name} </h1>`);
        }
        htmlEnd(res);
    }
    catch(err) {
        res.write(`<h1> uh oh: ${err.message} </h1>`);
        htmlEnd(res);
    }
})

app.listen(port,() => {
    console.log(`im listening! (on port ${port})`);
});